# CC Telegram Bridge Configuration Example
# Copy this file to ~/.cc_telegram/config.toml and configure
# NOTE: Telegram bot token, allowed users, and paths should be configured 
# in the .env file instead of here for security reasons

[telegram]
# Configuration will be loaded from environment variables:
# TELEGRAM_BOT_TOKEN - Your bot token from @BotFather
# TELEGRAM_ALLOWED_USERS - Comma-separated user IDs (e.g., "123456,789012")
timezone = "Europe/Madrid"
message_style = "concise"  # Options: "concise" (default), "detailed"

[paths]
# Paths will be loaded from environment variables:
# CC_TELEGRAM_EVENTS_DIR - Custom events directory (optional)
# CC_TELEGRAM_RESPONSES_DIR - Custom responses directory (optional)

[notifications]
# Enable/disable different types of notifications
task_completion = true
approval_requests = true
progress_updates = false

[security]
# Rate limiting settings
rate_limit_requests = 30 # Max requests per window
rate_limit_window = 60   # Window in seconds
audit_log = true         # Enable audit logging

[performance]
memory_threshold_mb = 100
cpu_threshold_percent = 80.0
event_processing_threshold_ms = 1000
telegram_response_threshold_ms = 5000
metrics_collection_interval_seconds = 30
enable_detailed_logging = false

[monitoring]
health_check_port = 8080
enable_metrics_server = true
metrics_endpoint = "/metrics"
health_endpoint = "/health"
