# Prometheus configuration for CCTelegram MCP Server monitoring

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'cctelegram-mcp'
    environment: '${ENVIRONMENT:-production}'

# Rules for alerting
rule_files:
  - "alert_rules.yml"

# Scrape configurations
scrape_configs:
  # MCP Server metrics
  - job_name: 'mcp-server'
    static_configs:
      - targets: ['mcp-server:3000']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s
    
    # Basic authentication if enabled
    basic_auth:
      username: 'prometheus'
      password: '${PROMETHEUS_PASSWORD:-prometheus}'
    
    # Relabeling for better metric organization
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'mcp-server'
      - source_labels: [job]
        target_label: service
        replacement: 'cctelegram-mcp'

  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s

  # Node exporter for system metrics (if available)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093