apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    basicAuth: false
    withCredentials: false
    jsonData:
      timeInterval: '10s'
      queryTimeout: '60s'
      httpMethod: POST
      customQueryParameters: 'max_source_resolution=5m&step=10s'
    secureJsonData: {}

  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    isDefault: false
    editable: true
    basicAuth: false
    withCredentials: false
    jsonData:
      maxLines: 1000
      timeout: 60
      derivedFields:
        - datasourceUid: Prometheus
          matcherRegex: 'correlation_id=([\\w-]+)'
          name: correlation_id
          url: '/explore?orgId=1&left=%5B%22now-1h%22,%22now%22,%22Prometheus%22,%7B%22expr%22:%22cctelegram_tier_requests_total%7Bcorrelation_id%3D%5C%22$${__value.raw}%5C%22%7D%22%7D%5D'
    secureJsonData: {}